# application name
spring:
  application:
    name: @spring.application.name@

# port
server:
  port: @server.port@
  tomcat:
    uri-encoding: UTF-8
    # 最大线程数
    max-threads: @server.tomcat.max-threads@
    # 最大连接数
    max-connections: @server.tomcat.max-connections@
    # 临时文件存放位置
#    basedir: /data1/tmp/@spring.application.name@
  servlet:
    context-path: /auth

---
# 多语言配置
spring:
  messages:
    # #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
    basename: messages/messages-system,messages/messages-redis,messages/messages-lock
    # 设置是否始终应用MessageFormat规则，甚至解析不带参数的消息
    always-use-message-format: true
    # #设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
    cache-seconds: 3600
    # 设定Message bundles的编码，默认: TF-8
    encoding: UTF-8
    # 设置如果找不到特定区域设置的文件，是否返回到系统区域设置。
    fallback-to-system-locale: false
---
## redis config
spring:
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    host: @spring.redis.host@
    port: @spring.redis.port@
    # 连接超时时间（毫秒）
    timeout: @spring.redis.timeout@
    password: @spring.redis.password@
      #集群配置
      #cluster:
      #nodes: #192.168.211.134:7000,192.168.211.134:7001
      #max-redirects: 5
      #哨兵配置
      #sentinel:
      #master: master1
    #nodes: # 172.16.33.216:16001,172.16.33.216:16002
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: @spring.redis.lettuce.pool.max-active@
        # 连接池中的最大空闲连接
        max-idle: @spring.redis.lettuce.pool.max-idle@
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: @spring.redis.lettuce.pool.max-wait@
        # 连接池中的最小空闲连接
        min-idle: @spring.redis.lettuce.pool.min-idle@

#开启断路器 新版本的fegin自带断路器
feign:
  hystrix:
    enabled: true

#ribbon请求连接的超时时间- 限制3秒内必须请求到服务，并不限制服务处理的返回时间
#ribbonTimeout = (ribbonReadTimeout + ribbonConnectTimeout) * (maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1);
#ribbonTimeout = (15000 + 3000) * (1 + 0) * (1 + 1) = 36000
# ribbon config
ribbon:
  #ribbon请求连接的超时时间- 限制2秒内必须请求到服务，并不限制服务处理的返回时间
  ConnectTimeout: 3000
  #请求处理的超时时间 下级服务响应最大时间,超出时间消费方（路由也是消费方）返回timeout
  ReadTimeout: 6000
  #对当前实例的重试次数
  MaxAutoRetries: 0
  #切换实例的重试次数 1
  MaxAutoRetriesNextServer: 1
  #ServerList缓存时间
  ServerListRefreshInterval: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #熔断超时时间
            timeoutInMilliseconds: 10000
        timeout:
          #是否启用超时时间
          enabled: true


management:
  endpoints:
    web:
      exposure:
        # 开放监控内容
        include: "*"
  endpoint:
    shutdown:
      enabled: true #启用shutdown端点
    health:
      # health/detail 细节（）
      show-details: always

## 日志配置
logging:
  config: classpath:logs/logback-spring.xml

# swagger 开关 true为开启，false或没有为关闭
swagger:
  enable: @swagger.enable@

---
#控制台输出彩色
spring:
  output:
    ansi:
      enabled: always