## 应用名称
spring:
  application:
    name: eureka-server

## 端口号
server:
  port: 8762

eureka:
  instance:
    hostname: eureka-server1
  client:
    ##这里要覆盖application的设置，不然会读取application文件导致unavailable-replicas
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server1:8763/eureka/