# application name
spring:
  application:
    name: multi-redis

# port
server:
  port: 8888

---
spring:
  multiple-redis:
    redis1:
      # 默认 localhost
      host: 127.0.0.1
      # 默认 6379
      port: 6379
      # Redis数据库索引（默认为0）
      database: 1
      # 超时时间
      timeout: 3000
      # 密码
      # password:
      #      # 集群模式
      #      cluster:
      #        # 最大的重定向次数
      #        max-redirects: 10
      #        nodes: 192.168.88.127:6381,192.168.88.127:6382
      #      # 哨兵方式
      #      sentinel:
      #        master: mymaster
      #        nodes: 192.168.88.128:26379, 192.168.88.128:26380
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）默认8
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认8
          min-idle: 0
    redis2:
      host: 127.0.0.1
      port: 6379
      database: 2
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

    redis3:
      host: 127.0.0.1
      port: 6379
      database: 3
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
---
#控制台输出彩色
spring:
  output:
    ansi:
      enabled: always

