## application name
spring:
  application:
    name: oauth2-jwt-authserver-server

server:
  port: 8999
  tomcat:
    uri-encoding: UTF-8
    # 最大线程数 #默认200
    max-threads: 200
    # 接受和处理的最大连接数 默认10000
    max-connections: 10000
    # 最大排队数 默认100
    accept-count: 100
    #默认10 初始化时创建的线程数 适当增大一些，以便应对突然增长的访问量100
    min-spare-threads: 50

# 允许/actuator/bus-refresh接口被外部调用
management:
  endpoints:
    web:
      exposure:
        # 开放监控内容
        include: "*"
  endpoint:
    shutdown:
      enabled: true #启用shutdown端点
    health:
      # health/detail 细节（）
      show-details: always


# swagger 开关 true为开启，false或没有为关闭
swagger:
  enable: true

## 日志配置
logging:
  config: classpath:logs/logback-spring.xml
  path: /Users/hx/logs
  level:
    # 全局日志级别
    default: INFO
    # 项目日志级别
    project: INFO
    # mybatis日志级别
    mybatis: DEBUG
---
#控制台输出彩色
spring:
  output:
    ansi:
      enabled: always
## ------------------------------业务相关配置写到下面-------------------------